version: '{build}'

image: Visual Studio 2015

build_script:
  - ps: |
      $outpath = (Get-Location).Path

      Set-Location C:\tools\vcpkg
      # Create our own custom triplet, for static-linking of libraries, but dynamic CRT linkage.
      Set-Content -Path "triplets/x86-windows-static-dyncrt.cmake" -Value "set(VCPKG_TARGET_ARCHITECTURE x86)`nset(VCPKG_CRT_LINKAGE dynamic)`nset(VCPKG_LIBRARY_LINKAGE static)`n"
      git pull 2> $null
      bootstrap-vcpkg.bat
      if ($lastExitCode -ne 0) { throw "Failed to update vcpkg" }
      vcpkg install curl[sspi] expat freetype libjpeg-turbo libogg libpng `
          libtheora libvorbis libvpx openssl opus pcre speex string-theory `
          zlib --triplet x86-windows-static-dyncrt
      if ($lastExitCode -ne 0) { throw "Failed to build static libs" }
      vcpkg install python2 --triplet x86-windows
      if ($lastExitCode -ne 0) { throw "Failed to build dynamic libs" }

      vcpkg list

      Set-Location C:\tools\vcpkg\installed\x86-windows-static-dyncrt
      7z a $outpath\devlibs.zip debug\lib include lib misc share
      if ($lastExitCode -ne 0) { throw "Failed to archive static libs" }
      Set-Location C:\tools\vcpkg\installed\x86-windows
      7z a $outpath\devlibs.zip bin debug\bin debug\lib include lib share
      if ($lastExitCode -ne 0) { throw "Failed to archive dynamic libs" }

artifacts:
  - path: devlibs.zip
