version: '{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PREFIX_MSVC: 2013
      PREFIX_ARCH: x86
      PREFIX_STATIC: ON

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PREFIX_MSVC: 2013
      PREFIX_ARCH: x86
      PREFIX_STATIC: OFF

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PREFIX_MSVC: 2015
      PREFIX_ARCH: x86
      PREFIX_STATIC: ON

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PREFIX_MSVC: 2015
      PREFIX_ARCH: x86
      PREFIX_STATIC: OFF

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PREFIX_MSVC: 2017
      PREFIX_ARCH: x86
      PREFIX_STATIC: ON

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PREFIX_MSVC: 2017
      PREFIX_ARCH: x86
      PREFIX_STATIC: OFF

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PREFIX_MSVC: 2017
      PREFIX_ARCH: x64
      PREFIX_STATIC: ON

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PREFIX_MSVC: 2017
      PREFIX_ARCH: x64
      PREFIX_STATIC: OFF

build_script:
  - mkdir build && cd build
  - if [%PREFIX_STATIC%]==[ON] (
      set "PREFIX_DIR=prefix-vc%PREFIX_MSVC%-%PREFIX_ARCH%-static"
    ) else (
      set "PREFIX_DIR=prefix-vc%PREFIX_MSVC%-%PREFIX_ARCH%"
    )
  - cmake -DBUILD_STATIC_LIBS=%PREFIX_STATIC% -DBUILD_ARCH=%PREFIX_ARCH%
      -DMSVC_VERSION=%PREFIX_MSVC%
      -DINSTALL_DIR="%APPVEYOR_BUILD_FOLDER%/%PREFIX_DIR%" ..
  - cmake --build .
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - cmake -E tar cf %PREFIX_DIR%.zip --format=zip %PREFIX_DIR%

artifacts:
  - path: prefix-*.zip
